{
 "title": "C* Cluster Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rate",
    "query": "30s,1m,5m,10m,15m,30m,1h,2h,3h,6h,12h,24h"
   },
   { "name": "jobname", "label": "Job name of Cassandra exporter", "query": "${VAR_JOBNAME}" },
   {
    "name": "instance",
    "query": "label_values(up{job=\"$jobname\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pending Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (threadpools) (sum_over_time(cassandra_threadpools_pendingtasks{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ threadpools }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (cache) (cassandra_cache_oneminutehitrate{instance=~\"$instance\"})",
     "legendFormat": "{{ cache }}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (threadpools) (sum_over_time(cassandra_threadpools_activetasks{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ threadpools }}"
    }
   ]
  },
  {
   "title": "Native Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$instance\",area=\"heap\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gossip Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(cassandra_connection_gossipmessagecompletedtasks{instance=~\"$instance\"}[$rate]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}